name: Node.js CI # Nome do workflow

on:
  push:
    branches: [ main] # Executa quando há push nessas branches
  pull_request:
    branches: [ main] # Executa quando há pull request nessas branches

jobs:
  build: # Nome do job
    runs-on: ubuntu-latest # O job será executado em uma máquina virtual Ubuntu

    steps:
    - name: Checkout repository # Passo para clonar o repositório
      uses: actions/checkout@v4

    - name: Set up Node.js # Passo para instalar o Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20' # Versão do Node.js utilizada

    - name: Install dependencies # Instala as dependências do projeto
      run: npm install

    - name: Run tests controller # Executa os testes automatizados de controller 
      run: npm run test-controller

    - name: Upload report test-controller
      uses: actions/upload-artifact@v4
      with:
        name: mochawesome-report test-controller
        path: mochawesome-report-test-controller/

    - name: Start Api # Inicia a API
      run: npm start &
    
    - name: Wait api
      run: sleep 5


    - name: Run tests external #Realiza testes externos ou seja com API oN
      run: npm rum test-external 

    - name: Upload report test-external
      uses: actions/upload-artifact@v4
      with:
        name: mochawesome-report test-external
        path: mochawesome-report-test-external/

    - name: Run ALL tests  #Realiza testes externos ou seja com API oN
      run: npm test

    - name: Upload report tests
      uses: actions/upload-artifact@v4
      with:
        name: mochawesome-report tests
        path: mochawesome-report-tests/